#!/bin/bash
set -euo pipefail

RESET='\033[0m'
RED='\033[1;31m'
YELLOW='\033[0;33m'
YELLOWB='\033[1;33m'
WHITEB='\033[1;37m'

exe() { echo "\$ $@" ; "$@" ; }

CHANGED_FILES="$(git diff --name-only --cached --diff-filter=ACMR -- '*.py')"

# Get only changed files that match our file suffix pattern
get_pattern_files() {
    echo "$CHANGED_FILES" | { grep "${1}$" || true; }
}

PADDING="......................................"

# Get all changed python files
PY_FILES=$(get_pattern_files .py)

# Filter out list to only check py files
if [[ -n ${CHANGED_FILES} ]]; then
    echo -e "${WHITEB}Checking python files via flake8...${RESET}"
    flake8 ${PY_FILES}

    TITLE="flake8"
    printf "%s%s %s\n" "$TITLE" "${PADDING:${#TITLE}}" "Passed"
    #printf "%-25s %5s" "${WHITEB}flake8" "Passed${RESET}"

    echo -e "${WHITEB}Checking python files via black...${RESET}"
    black --check ${PY_FILES}
    TITLE="black"
    printf "%s%s %s\n" "$TITLE" "${PADDING:${#TITLE}}" "Passed"
    # printf "%-25s %5s" "${WHITEB}black" "Passed${RESET}"
fi
